import Link from "next/link";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>
          <Link href="./">App Router: Dynamic routing from API request</Link>
        </h1>
        {children}
      </body>
    </html>
  );
}
